# Generated by Django 5.2.7 on 2025-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_newsletter"),
        ("publishers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="articles_published",
            field=models.ManyToManyField(blank=True, to="articles.article"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="journalist_subscribed",
            field=models.ManyToManyField(blank=True, to="users.userprofile"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="newsletters_published",
            field=models.ManyToManyField(blank=True, to="articles.newsletter"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="publisher_subscribed",
            field=models.ManyToManyField(blank=True, to="publishers.publisher"),
        ),
    ]
