# Generated by Django 5.2.7 on 2025-10-31 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=25)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="article_images/"
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishers.publisher",
                    ),
                ),
            ],
        ),
    ]
