# Generated by Django 5.2.7 on 2025-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
