# Generated by Django 5.2.7 on 2025-11-14 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("api_key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subscribed_journalists",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Journalist"},
                        related_name="api_subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscribed_publishers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Publisher"},
                        related_name="api_publisher_subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
