# Generated by Django 5.2.7 on 2025-11-14 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_apiclient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiclient",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "Journalist"},
                related_name="api_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "Publisher"},
                related_name="api_publisher_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
