# Generated by Django 5.2.7 on 2025-11-12 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="publishers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
